version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=production
